application:
  http_bind_address: 127.0.0.1
  http_listen_port: 8000
  base_url: http://127.0.0.1
  hmac_secret: some-very-long-and-secure-secret-key-1234567890-qwertyuuiop-asdfghjkl
database:
  hostname: 127.0.0.1
  port: 5432
  username: app
  password: secret
  database_name: newsletter
  require_ssl: false
email_client:
  base_url: localhost
  sender_email: test@gmail.com
  authorization_token: secret-token
  timeout_milliseconds: 10000
redis_uri: redis://127.0.0.1:6379
